apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: crud-app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mongo-ebs
  resources:
    requests:
      storage: 10Gi
